### ISSUE TITLE
Question!

### ISSUE THREAD

**Issue by meysam81** [uestla/Sparse-Matrix#11]
Hello and thanks for your code
I'm trying to understand the following piece of your code and I seem to have a trouble doing that so I referred here.
```
vector<T> * vals;
vector<int> * rows, * cols;
```

I can't understand the reason behind making a vector of pointers and if you could guide me in the right direction, I'd be grateful.

**Comment by uestla** [comment]
Hello!
Those are actually not vectors of pointers but pointers to vectors.

I did it like so just not to waste memory with empty vector when the matrix itself is empty.
But these vectors get instantiated e.g. when first non-zero value is inserted: 

https://github.com/uestla/Sparse-Matrix/blob/7451ac799703c3853ff97a73c37739af1b8c812b/src/SparseMatrix/SparseMatrix.cpp#L316-L317

**Comment by meysam81** [comment]
Another question if you don't mind me asking, and I wouldn't wanna open a new issue as the topic would be the same

Firstly how did you do what you did in the end of your reply (the link to the code), and it may sound silly but it is best to ask than being in the gloom forever

And secondly how would you interpret the code below in a human readable format:
```
this->rows = new vector<int>(*(matrix.rows));
```
Precisely I mean the right hand side of the assignment as my question is undoubtedly mentioning

And thanks again for your consideration

**Comment by uestla** [comment]
The block of code is created by GitHub, I just copied the URL of the lines, which is:

```
https://github.com/uestla/Sparse-Matrix/blob/7451ac799703c3853ff97a73c37739af1b8c812b/src/SparseMatrix/SparseMatrix.cpp#L316-L317
```

You can try it yourself (paste it in the comment box and display *Preview*) ;-)

---

The assignment is just creating a deep copy of a vector (via copy constructor). It's more a C++ thing than something specific for my library.
